### ISSUE TITLE
BridgeConfiguration.InterceptForawrding() not available for NServiceBus v7

### ISSUE THREAD

**Issue by SeanFeldman** [SzymonPobiega/NServiceBus.Bridge#10]
Is available for NServiceBus v6
https://github.com/SzymonPobiega/NServiceBus.Bridge/blob/81358d3354b6d89542f83311fbfa65e94069c5b8/src/NServiceBus.Bridge/BridgeConfiguration.cs#L40

**Comment by SzymonPobiega** [comment]
Added in https://github.com/SzymonPobiega/NServiceBus.Bridge/commit/ce8e5dfca31cc62e36ff3eadea1ee487be8b12e1 and fixed the typo in the name.
