### ISSUE TITLE
Typos in public API

### ISSUE THREAD

**Issue by SeanFeldman** [SzymonPobiega/NServiceBus.Bridge#11]
> BridgeConfiguration.InterceptForawrding()
https://github.com/SzymonPobiega/NServiceBus.Bridge/blob/81358d3354b6d89542f83311fbfa65e94069c5b8/src/NServiceBus.Bridge/BridgeConfiguration.cs#L40

Should be BridgeConfiguration.Intercept**Forwarding**()

>  BridgeConfiguration.UseSubscriptionPersistece<>()
https://github.com/SzymonPobiega/NServiceBus.Bridge/blob/81358d3354b6d89542f83311fbfa65e94069c5b8/src/NServiceBus.Bridge/BridgeConfiguration.cs#L30

Should be BridgeConfiguration.UseSubscription**Persistence**<>()

**Comment by SzymonPobiega** [comment]
Fixed in https://github.com/SzymonPobiega/NServiceBus.Bridge/commit/ce8e5dfca31cc62e36ff3eadea1ee487be8b12e1 for 2.0 release. Won't be able to fix it for 1.1 because that would be a breaking change :-(

**Comment by SeanFeldman** [comment]
For 1.1, let's release it as 1.2 with the old methods obsoleted.
