### ISSUE TITLE
Can a single bridge connect multiple endpoints?

### ISSUE THREAD

**Issue by SeanFeldman** [SzymonPobiega/NServiceBus.Bridge#19]
For endpoinst `A` and `B` to talk to each other, a `Bridge` is needed.
If a third endpoint is added, `C`, to talk to other endpoints, would it require:
- A bridge process per endpoint it wants to target (a bridge to talk `A` and a bridge to talk to `B`)?
- Or will it be able to use the already existing `Bridge`?

**Comment by SeanFeldman** [comment]
The short answer - mutliple endpoint can communicate through the same transport.
![image](https://user-images.githubusercontent.com/1309622/39226708-5449a650-4811-11e8-99ba-7580511394f6.png)

**Comment by SzymonPobiega** [comment]
I've updated the doco https://docs.particular.net/nservicebus/bridge/?version=bridge_2 with some topology examples
