### ISSUE TITLE
NServiceBus version

### ISSUE THREAD

**Issue by SeanFeldman** [SzymonPobiega/NServiceBus.Bridge#9]
https://github.com/SzymonPobiega/NServiceBus.Bridge/blob/6c1c32b1624077f012bc2a5d4ed5521bfbc28c9f/src/NServiceBus.Bridge.Connector/BridgeSubscribeBehavior.cs#L41

The comment says "version the code was copied from", but the header reads as "NServiceBus version used to generate this message". What is it?

**Comment by SzymonPobiega** [comment]
This code has been copied from the `SubscribeTerminator` of NSB 6.3.1. Unfortunately due to design limitation that terminator cannot be reused here (it is a terminator and Raw needs a regular behavior). The comment is a reminder to copy a fresh version if applicable.
